### ISSUE TITLE
pip install and update

### ISSUE THREAD

**Issue by jmjech** [ices-tools-dev/echoSMs#28]
Quick update and not necessarily an issue. 
I needed to uninstall, then install echosms on my google workstation (linux Ubuntu VM) and on my linux box to get the latest version. I suspect it's been that way because I was on version 0.1.8 on the GWS and 0.1.7 on my linux box, even though I'm pretty sure I've installed a few times between those and the new version. Do you know if pip install -U will work?

**Comment by gavinmacaulay** [comment]
Use `pip install echosms --upgrade` (or -U) otherwise it won't replace an existing install (or `pip uninstall echosms` and then `pip install echosms`).

I've added this to documentation now (won't show up there yet though).

**Comment by gavinmacaulay** [comment]
Closing as doc is now updated online.
